# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9167e4982af4da6f250880ce88e7d0029353d231f0c40a476e3272d30550a8c30dc6787485c7c501ce254eb7cbab169cf13051e66ce08a7e62cbeaa83ef51e9c

test:
  secret_key_base: e4c0ed12ec39ef40a393b4f36424346be76a7cb5e10d6c5eacf32c584bfef5b68b30dab1402e2a1eea09fbbef883786518fd868816b01b6ec0547503abb578fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
